In [2]:
from locale import currency
import numpy as np

In [3]:
# Setting up the board and the Q-matrix

R = np.matrix([[-0.04,-0.04,-0.04,1],
               [-0.04,-1000,-0.04,-1],
               [-0.04,-0.04,-0.04,-0.04]])

Q=np.matrix(np.zeros([3,4]))

print(R)
print(Q)

[[-4.e-02 -4.e-02 -4.e-02  1.e+00]
 [-4.e-02 -1.e+03 -4.e-02 -1.e+00]
 [-4.e-02 -4.e-02 -4.e-02 -4.e-02]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
alpha = 0.8

initial_state=0

In [19]:
def available_actions(state):
    curr_state_row = R[state,]
    av_act = np.where(curr_state_row>=0)[1]
    return av_act,curr_state_row

available_act,test = available_actions(initial_state)
print(available_act)
test

[3]


In [20]:
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action


In [23]:
action = sample_next_action(available_act)
action

3

In [25]:
def update (current_state, action, alpha):
    max_index = np.where(Q[action-1,]==np.max(Q[action-1,]))[1]

    if (max_index.shape[0] > 1):
        max_index = int (np.random.choice(max_index, size=1))
    else:
        max_index = int(max_index)
    max_value = Q[action-1, max_index]

    #Q learning formula
    Q[current_state,action-1] = R[current_state, action-1] + alpha*max_value

update(initial_state, action, alpha)

In [29]:
for i in range (10000):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state, action, alpha)

print("Trained Q matrix")
print(Q/np.max(Q)* 100)

ValueError: 'a' cannot be empty unless no samples are taken